# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jeppe/repo/eemr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jeppe/repo/eemr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeppe/repo/eemr/CMakeFiles /home/jeppe/repo/eemr//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jeppe/repo/eemr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cv-hw

# Build rule for target.
cv-hw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cv-hw
.PHONY : cv-hw

# fast build rule for target.
cv-hw/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv-hw.dir/build.make CMakeFiles/cv-hw.dir/build
.PHONY : cv-hw/fast

#=============================================================================
# Target rules for targets named cv-sw

# Build rule for target.
cv-sw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cv-sw
.PHONY : cv-sw

# fast build rule for target.
cv-sw/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv-sw.dir/build.make CMakeFiles/cv-sw.dir/build
.PHONY : cv-sw/fast

#=============================================================================
# Target rules for targets named cv-ic

# Build rule for target.
cv-ic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cv-ic
.PHONY : cv-ic

# fast build rule for target.
cv-ic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cv-ic.dir/build.make CMakeFiles/cv-ic.dir/build
.PHONY : cv-ic/fast

#=============================================================================
# Target rules for targets named clean_aux

# Build rule for target.
clean_aux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_aux
.PHONY : clean_aux

# fast build rule for target.
clean_aux/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_aux.dir/build.make CMakeFiles/clean_aux.dir/build
.PHONY : clean_aux/fast

#=============================================================================
# Target rules for targets named clean_biber

# Build rule for target.
clean_biber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_biber
.PHONY : clean_biber

# fast build rule for target.
clean_biber/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_biber.dir/build.make CMakeFiles/clean_biber.dir/build
.PHONY : clean_biber/fast

#=============================================================================
# Target rules for targets named clean_all

# Build rule for target.
clean_all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_all
.PHONY : clean_all

# fast build rule for target.
clean_all/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_all.dir/build.make CMakeFiles/clean_all.dir/build
.PHONY : clean_all/fast

#=============================================================================
# Target rules for targets named rebuild

# Build rule for target.
rebuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rebuild
.PHONY : rebuild

# fast build rule for target.
rebuild/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/rebuild.dir/build.make CMakeFiles/rebuild.dir/build
.PHONY : rebuild/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clean_all"
	@echo "... clean_aux"
	@echo "... clean_biber"
	@echo "... cv-hw"
	@echo "... cv-ic"
	@echo "... cv-sw"
	@echo "... rebuild"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

